### PR TITLE
Add phishing sites to blocklist

### PR DESCRIPTION
**Pull request by anishshandilya**
Add phishing sites to blocklist for the entities we are responsible for.

### CODE REVIEW

**Comment by Harii94** [comment]
adding these manually after verifying them, thanks Anish!

**Comment by Harii94** [comment]
@anishshandilya Please add the domains which are not taken down yet. There are multiple domains that are not live anymore.

**Comment by anishshandilya** [comment]
@Harii94 Thanks for taking a look! When we first submitted, all these sites were up, but it looks like there is a delay between when we first submit this, and the time it gets merged.

Is there any way we can resolve this without having to continuously check?

**Comment by topazso** [comment]
@anishshandilya Why did you add Topaz.so?

**Pull request closed without merging**
