### PR TITLE
Add phishing sites to blocklist

### PR DESCRIPTION
**Pull request by anishshandilya**
Add phishing sites to blocklist for magiceden

### CODE REVIEW

**Comment by Harii94** [comment]
Hey, I'm not able to validate safeaptos.com nor does it directly impact Phantom users.

**Comment by anishshandilya** [comment]
Hey! Sorry this is our first time contributing to this repo.

At Doppel, one of the things we do is scan for and report phishing sites.

safeaptos.com is a phishing site of aptoslabs.com.

Do you not protect against these use cases?

**Comment by Harii94** [comment]
Can you please provide proof that safeaptos.com is a phishing website?

**Comment by anishshandilya** [comment]
I just removed safeaptos as its technically impersonation. Please see that the others are fit! Also please let us know if there's anything we can help with speeding up the process in the future!

**Comment by anishshandilya** [comment]
@Harii94 Just a friendly reminder here! We are actively working with MagicEden and Veefriends directly to make sure these are blocked in a timely manner.

**Review by Harii94 — CHANGES_REQUESTED** [review]
Can you remove magiceden.autoflare.io from the list? We don't block subdomains yet.

**Comment by anishshandilya** [comment]
@Harii94 Sounds good! We will add that check moving forward. I have updated the PR!

**Pull request merged**
